name: keeper

services:
  postgres:
    image: postgres:17
    container_name: keeper-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - keeper-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keeper-postgres-data:
